# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vizija.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VizijaProjekat(object):
    def setupUi(self, VizijaProjekat):
        VizijaProjekat.setObjectName(_fromUtf8("VizijaProjekat"))
        VizijaProjekat.resize(800, 600)
        self.centralwidget = QtGui.QWidget(VizijaProjekat)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 460, 201, 61))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 170, 68, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 420, 119, 88))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.radioButton = QtGui.QRadioButton(self.widget)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(VizijaProjekat)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout_4.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.widget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.widget)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup.addButton(self.radioButton_3)
        self.verticalLayout_4.addWidget(self.radioButton_3)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(560, 30, 196, 225))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.widget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.checkBox = QtGui.QCheckBox(self.widget1)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.buttonGroup_2 = QtGui.QButtonGroup(VizijaProjekat)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.checkBox)
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.widget1)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.buttonGroup_2.addButton(self.checkBox_2)
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.widget1)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.buttonGroup_2.addButton(self.checkBox_3)
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.widget1)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.buttonGroup_2.addButton(self.checkBox_4)
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_6 = QtGui.QCheckBox(self.widget1)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.buttonGroup_2.addButton(self.checkBox_6)
        self.verticalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_8 = QtGui.QCheckBox(self.widget1)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.buttonGroup_2.addButton(self.checkBox_8)
        self.verticalLayout_3.addWidget(self.checkBox_8)
        self.checkBox_5 = QtGui.QCheckBox(self.widget1)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.buttonGroup_2.addButton(self.checkBox_5)
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        self.checkBox_8.raise_()
        self.pushButton.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.checkBox_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        VizijaProjekat.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(VizijaProjekat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        VizijaProjekat.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(VizijaProjekat)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        VizijaProjekat.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(VizijaProjekat)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(VizijaProjekat)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(VizijaProjekat)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButton.click)
        QtCore.QMetaObject.connectSlotsByName(VizijaProjekat)
        VizijaProjekat.setTabOrder(self.checkBox_2, self.checkBox_3)
        VizijaProjekat.setTabOrder(self.checkBox_3, self.checkBox_4)
        VizijaProjekat.setTabOrder(self.checkBox_4, self.checkBox_6)
        VizijaProjekat.setTabOrder(self.checkBox_6, self.checkBox_8)
        VizijaProjekat.setTabOrder(self.checkBox_8, self.checkBox_5)
        VizijaProjekat.setTabOrder(self.checkBox_5, self.radioButton)
        VizijaProjekat.setTabOrder(self.radioButton, self.radioButton_2)
        VizijaProjekat.setTabOrder(self.radioButton_2, self.radioButton_3)
        VizijaProjekat.setTabOrder(self.radioButton_3, self.pushButton)
        VizijaProjekat.setTabOrder(self.pushButton, self.checkBox)

    def retranslateUi(self, VizijaProjekat):
        VizijaProjekat.setWindowTitle(_translate("VizijaProjekat", "MainWindow", None))
        self.pushButton.setText(_translate("VizijaProjekat", "Realese the KRAKEN!!!", None))
        self.label_2.setText(_translate("VizijaProjekat", "TextLabel", None))
        self.radioButton.setText(_translate("VizijaProjekat", "RadioButton", None))
        self.radioButton_2.setText(_translate("VizijaProjekat", "RadioButton", None))
        self.radioButton_3.setText(_translate("VizijaProjekat", "RadioButton", None))
        self.label.setText(_translate("VizijaProjekat", "Morfologije", None))
        self.checkBox.setText(_translate("VizijaProjekat", "Erosion", None))
        self.checkBox_2.setText(_translate("VizijaProjekat", "Dilation", None))
        self.checkBox_3.setText(_translate("VizijaProjekat", "Opening", None))
        self.checkBox_4.setText(_translate("VizijaProjekat", "Closing", None))
        self.checkBox_6.setText(_translate("VizijaProjekat", "Morphological Gradient", None))
        self.checkBox_8.setText(_translate("VizijaProjekat", "Top Hat", None))
        self.checkBox_5.setText(_translate("VizijaProjekat", "Black Hat", None))
        self.menuFile.setTitle(_translate("VizijaProjekat", "File", None))
        self.actionOpen.setText(_translate("VizijaProjekat", "Open", None))
        self.actionSave.setText(_translate("VizijaProjekat", "Save", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    VizijaProjekat = QtGui.QMainWindow()
    ui = Ui_VizijaProjekat()
    ui.setupUi(VizijaProjekat)
    VizijaProjekat.show()
    sys.exit(app.exec_())

